// client-app/src/app/features/activities/dashboard/activity-dashboard/activity-dashboard.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {Activity} from "../../../../models/activity";

@Component({
  selector: 'app-activity-dashboard',
  templateUrl: './activity-dashboard.component.html',
  styleUrls: ['./activity-dashboard.component.css']
})
export class ActivityDashboardComponent implements OnInit {
  @Input() activities: Activity[];
  @Input() selectedActivity: Activity | null;
  @Input() selectActivity: (id: string) => void;
  @Input() cancelSelectActivity: () => void;
  @Input() editMode: boolean;
  @Input() openForm: (id: string) => void;
  @Input() closeForm: () => void;
  @Input() createOrEdit: (activity: Activity) => void;
  @Input() deleteActivity: (id: string) => void;

  constructor() {
  }

  ngOnInit(): void {
  }

}

<div class="row">
  <div class="col-8">
      <app-activity-list
        [activities]="activities"
        [selectActivity]="selectActivity"
        [deleteActivity]="deleteActivity"
      ></app-activity-list>
  </div>

  <div class="col-4">
    <app-activity-details
      *ngIf="selectedActivity && !editMode"
      [activity]="selectedActivity"
      [cancelSelectActivity]="cancelSelectActivity"
      [openForm]="openForm"
    ></app-activity-details>
    <app-activity-form
      [activity]="selectedActivity"
      *ngIf="editMode"
      [closeForm]="closeForm"
      [createOrEdit]="createOrEdit"
    ></app-activity-form>
  </div>
</div>

// clent-app/src/features/activities/dashboard/ActivityDashboard.tsx
import React from 'react';
import {Activity} from "../../../app/models/activity";
import {Grid} from "semantic-ui-react";
import ActivityList from "./ActivityList";
import ActivityDetails from "../details/ActivityDetails";
import ActivityForm from "../form/ActivityForm";

interface Props {
    activities: Activity[];
    selectedActivity: Activity | undefined;
    selectActivity: (id: string) => void;
    cancelSelectedActivity: () => void;
    editMode: boolean;
    openForm: (id: string) => void;
    closeForm: () => void;
    createOrEdit: (activity: Activity) => void;
    deleteActivity: (id: string) => void;
}

function ActivityDashboard({activities, selectActivity, selectedActivity, cancelSelectedActivity, openForm, closeForm, editMode, createOrEdit, deleteActivity}: Props) {
    return (
        <Grid>
            <Grid.Column width={'10'}>
                <ActivityList 
                    activities={activities} 
                    selectActivity={selectActivity}
                    deleteActivity={deleteActivity}
                />
            </Grid.Column>
            <Grid.Column width={'6'}>
                {selectedActivity && !editMode &&
                    <ActivityDetails 
                        selectedActivity={selectedActivity} 
                        cancelSelectedActivity={cancelSelectedActivity}
                        openForm={openForm}
                    />}
                {editMode &&
                <ActivityForm 
                    closeForm={closeForm}
                    activity={selectedActivity}
                    createOrEdit={createOrEdit}
                />}
            </Grid.Column>
        </Grid>
    )
}

export default ActivityDashboard;
