// client-app/src/app/layout/navbar/navbar.component.ts
import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {
  @Input() openForm: () => void;

  constructor() {
  }

  ngOnInit(): void {
  }

}

<div class="p-3 px-md-4 mb-3 fixed-top nav-bar">
  <div class="container d-flex flex-column flex-md-row align-items-center">
    <img src="assets/Images/logo.png" class="logo" alt="logo" title="logo">
    <nav class="my-2 my-md-0 mr-md-3">
      <a class="p-2 text-light" href="#">Activities</a>
    </nav>
    <a class="btn btn-success px-4" (click)="openForm()">Create Activity</a>
  </div>
</div>

// clent-app/src/app/layout/NavBar.tsx
import React from 'react';
import {Button, Container, Menu} from "semantic-ui-react";

interface Props {
    openForm: () => void;
}

function NavBar({openForm}: Props) {
    return (
        <Menu inverted fixed={"top"}>
            <Container>
                <Menu.Item header>
                    <img src="/assets/logo.png" alt="logo" style={{marginRight: '10px'}}/>
                    Reactivities
                </Menu.Item>
                <Menu.Item name="Activities"/>
                <Menu.Item>
                    <Button onClick={()=>openForm()} positive content="Create Activity"/>
                </Menu.Item>
            </Container>
        </Menu>
    )
}

export default NavBar;
