// clent-app/src/app/layout/App.tsx
import React, {useEffect, useState} from 'react';
import axios from "axios";
import {Activity} from "../models/activity";
import NavBar from "./NavBar";
import 'semantic-ui-css/semantic.min.css'
import ActivityDashboard from "../../features/activities/dashboard/ActivityDashboard";
import {Container} from "semantic-ui-react";
import {v4 as uuid} from 'uuid';

function App() {
    const [activities, setActivities] = useState<Activity[]>([]);
    const [selectedActivity, setSelectedActivity] = useState<Activity | undefined>(undefined);
    const [editMode, setEditMode] = useState(false);
    
    useEffect(() => {
        axios.get<Activity[]>('http://localhost:5148/api/activities').then(response => {
            setActivities(response.data);
        }).catch(error => {
            console.log(error);
        })
    }, [])

    function handleSelectActivity(id: string) {
        setSelectedActivity(activities.find(x => x.id === id));
    }
    
    function handleCancelSelectActivity(){
        setSelectedActivity(undefined);
    }
    
    function handleFormOpen(id?: string){
        id ? handleSelectActivity(id) : handleCancelSelectActivity();
        setEditMode(true);
    }
    
    function handleFormClose(){
        setEditMode(false);
    }
    
    function handleCreateOrEditActivity(activity: Activity){
        activity.id
            ? setActivities([...activities.filter(x => x.id !== activity.id), activity])
            : setActivities([...activities, {...activity, id: uuid()}]);
        setEditMode(false);
        setSelectedActivity(activity);
    }
    
    function handleDeleteActivity(id: string){
        setActivities([...activities.filter(x => x.id !== id)]);
    }
    
    return (
        <>
            <NavBar openForm={handleFormOpen}/>
            <Container style={{marginTop: '7em'}}>
                <ActivityDashboard 
                    activities={activities}
                    selectedActivity={selectedActivity}
                    selectActivity={handleSelectActivity}
                    cancelSelectedActivity={handleCancelSelectActivity}
                    editMode={editMode}
                    openForm={handleFormOpen}
                    closeForm={handleFormClose}
                    createOrEdit={handleCreateOrEditActivity}
                    deleteActivity={handleDeleteActivity}
                />
            </Container>
        </>
    );
}

export default App;

// client-app/src/app/app.component.ts
import {Component, OnInit} from '@angular/core';
import {HttpClient} from "@angular/common/http";
import {Activity} from "./models/activity";
import {v4 as uuid} from 'uuid';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  activities: Activity[];
  selectedActivity: Activity | null;
  editMode: boolean = false;

  constructor(private http: HttpClient) {
  }

  ngOnInit(): void {
    this.http.get<Activity[]>('http://localhost:5000/api/activities').subscribe((activities: Activity[]) => {
      this.activities = activities;
    })
  }

  handleSelectedActivity = (id: string) => {
    this.selectedActivity = this.activities.find(x => x.id === id);
  }

  cancelSelectedActivity = () => {
    this.selectedActivity = null;
  }

  handleFormOpen = (id?: string) => {
    id ? this.handleSelectedActivity(id) : this.cancelSelectedActivity();
    this.editMode = true;
  }

  handleFormClose = () => {
    this.editMode = false;
  }

  handleCreateOrEditActivity = (activity: Activity) => {
    activity.id
      ? this.activities = [...this.activities.filter(x => x.id !== activity.id), activity]
      : this.activities = [...this.activities, {...activity, id: uuid()}];
    this.editMode = false;
    this.selectedActivity = activity;
  }

  handleDeleteActivity = (id: string) => {
    this.activities = [...this.activities.filter(x => x.id !== id)];
  }
}

<app-navbar [openForm]="handleFormOpen"></app-navbar>


<div class="container" style="margin-top: 7em;">
  <app-activity-dashboard
    [activities]="activities"
    [selectedActivity]="selectedActivity"
    [selectActivity]="handleSelectedActivity"
    [cancelSelectActivity]="cancelSelectedActivity"
    [editMode]="editMode"
    [openForm]="handleFormOpen"
    [closeForm]="handleFormClose"
    [createOrEdit]="handleCreateOrEditActivity"
    [deleteActivity]="handleDeleteActivity"
  ></app-activity-dashboard>
</div>
