// clent-app/src/App.tsx
import React, {useEffect, useState} from 'react';
import './App.css';
import axios from "axios";

function App() {


    const [activities, setActivities] = useState([]);

    useEffect(() => {
        axios.get('http://localhost:5148/api/activities').then(response => {
            setActivities(response.data);
        }).catch(error => {
            console.log(error);
        })
    }, [])

    
    return (
        <div>
            <h1>Activity List</h1>
            {activities?.map((activity: any) => (
                <div key={activity.id}>{activity.title}</div>
            ))}
        </div>
    );
}

export default App;

// client-app/src/app/app.component.ts
import {Component, OnInit} from '@angular/core';
import {HttpClient} from "@angular/common/http";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit{
  title = 'client-app';
  activities: any;

  constructor(private http: HttpClient) {
  }

  ngOnInit(): void {
    this.http.get('http://localhost:5000/api/activities').subscribe(response=>{
      this.activities = response;
    })
  }
}

<h3>
  <i class="fa fa-user"></i> Reactivities
</h3>

<ul>
  <li *ngFor="let activity of activities">{{activity.title}}</li>
</ul>
