// clent-app/src/features/activities/details/ActivityDetails.tsx
import React from 'react';
import {Button, Card, Image} from "semantic-ui-react";
import {Activity} from "../../../app/models/activity";

interface Props {
    selectedActivity: Activity
    cancelSelectedActivity: () => void;
    openForm: (id: string) => void;
    
}

function ActivityDetails({selectedActivity: activity, cancelSelectedActivity, openForm}: Props) {
    return (
        <Card fluid>
            <Image src={`/assets/categoryImages/${activity.category}.jpg`} wrapped ui={false}/>
            <Card.Content>
                <Card.Header>{activity.title}</Card.Header>
                <Card.Meta>
                    <span className='date'>{activity.date}</span>
                </Card.Meta>
                <Card.Description>
                    {activity.description}
                </Card.Description>
            </Card.Content>
            <Card.Content extra>
                <Button.Group widths={2}>
                    <Button onClick={() => openForm(activity.id)} basic color='blue' content='Edit'/>
                    <Button onClick={() => cancelSelectedActivity()} basic color='grey' content='Cancel'/>
                </Button.Group>
            </Card.Content>
        </Card>
    )
}

export default ActivityDetails;

// client-app/src/app/features/activities/details/activity-details/activity-details.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {Activity} from "../../../../models/activity";

@Component({
  selector: 'app-activity-details',
  templateUrl: './activity-details.component.html',
  styleUrls: ['./activity-details.component.css']
})
export class ActivityDetailsComponent implements OnInit {
  @Input() activity: Activity;
  @Input() cancelSelectActivity: () => void;
  @Input() openForm: (id: string) => void;

  constructor() {
  }

  ngOnInit(): void {
  }



}

<div class="card shadow-sm">
  <img src="assets/Images/categoryImages/{{activity.category}}.jpg" class="img-fluid">

  <div class="card-body">
    <h4>{{activity.title}}</h4>
    <span class="small text-muted">{{activity.date}}</span>
    <p class="card-text">{{activity.description}}</p>
      <div class="btn-group d-flex">
        <button type="button" class="btn btn-sm btn-outline-primary" (click)="openForm(activity.id)">Edit</button>
        <button type="button" class="btn btn-sm btn-outline-secondary" (click)="cancelSelectActivity()">Cancel</button>
      </div>
  </div>
</div>
