// clent-app/src/features/activities/form/ActivityForm.tsx
import React, {useState} from 'react';
import {Button, Form, Segment} from "semantic-ui-react";
import {Activity} from "../../../app/models/activity";

interface Props {
    closeForm: () => void;
    activity: Activity | undefined;
    createOrEdit: (activity: Activity) => void;
}

// initial state of activity


function ActivityForm({closeForm, activity: selectedActivity, createOrEdit}: Props) {
    const initialFormState = selectedActivity ?? {
        id: '',
        title: '',
        category: '',
        description: '',
        date: '',
        city: '',
        venue: ''
    }

    const [activity, setActivity] = useState(initialFormState);

    function handleSubmit() {
        createOrEdit(activity);
    }
    
    function handleInputChange(event: any) {
        const {name, value} = event.target;
        setActivity({...activity, [name]: value})
    }
    
    return (
        <Segment clearing>
            <Form onSubmit={handleSubmit} autoComplete={'off'}>
                <Form.Input placeholder='Title' onChange={handleInputChange} value={activity.title} name={'title'}/>
                <Form.TextArea rows={2} onChange={handleInputChange} value={activity.description} name={'description'} placeholder='Description'/>
                <Form.Input onChange={handleInputChange} value={activity.category} name={'category'} placeholder='Category'/>
                <Form.Input onChange={handleInputChange} value={activity.date} name={'date'} placeholder='Date'/>
                <Form.Input onChange={handleInputChange} value={activity.city} name={'city'} placeholder='City'/>
                <Form.Input onChange={handleInputChange} value={activity.venue} name={'venue'} placeholder='Venue'/>
                <Button floated='right' positive type='submit' content='Submit'/>
                <Button onClick={() => closeForm()} floated='right' type='button' content='Cancel'/>
            </Form>
        </Segment>
    )

}

export default ActivityForm;

// client-app/src/app/features/activities/form/activity-form/activity-form.component.ts
import {Component, Input, OnInit, ViewChild} from '@angular/core';
import {Activity} from "../../../../models/activity";
import {NgForm} from "@angular/forms";

@Component({
  selector: 'app-activity-form',
  templateUrl: './activity-form.component.html',
  styleUrls: ['./activity-form.component.css']
})
export class ActivityFormComponent implements OnInit {
  @Input() activity: Activity;
  @Input() closeForm: () => void;
  @ViewChild('activityForm') activityForm: NgForm;
  @Input() createOrEdit: (activity: Activity) => void;

  constructor() {

  }

  ngOnInit(): void {
    this.setActivity();
  }

  setActivity() {
    this.activity = this.activity ?? {
      id: '',
      title: '',
      category: '',
      description: '',
      date: '',
      city: '',
      venue: ''
    }
  }

  handleSubmit() {
    let activityToReturn = {...this.activityForm.value, id: this.activity.id};
    this.createOrEdit(activityToReturn);
  }

}

<div class="card">
  <div class="card-body">
    <form #activityForm = "ngForm" (ngSubmit)="handleSubmit()">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Title" name="title" [ngModel]="activity.title">
      </div>
      <div class="form-group">
        <textarea class="form-control" rows="2" placeholder="Description" name="description" [ngModel]="activity.description">{{activity.description}}</textarea>
      </div>
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Category" name="category"  [ngModel]="activity.category">
      </div>
      <div class="form-group">
        <input type="text" class="form-control"  name="date"   placeholder="dd/mm/yyyy" bsDatepicker [ngModel]="activity.date">
      </div>
      <div class="form-group">
        <input type="text" class="form-control" name="city" placeholder="City" [ngModel]="activity.city">
      </div>
      <div class="form-group">
        <input type="text" class="form-control" name="venue" placeholder="Venue" [ngModel]="activity.venue">
      </div>
      <div class="form-group">
        <button class="btn btn-success float-right" type="submit">
          Submit</button>
        <button class="btn btn-secondary float-right mr-2" type="button" (click)="closeForm()">Cancel</button>
      </div>
    </form>
  </div>
</div>
